version: '3.8'

services:
  glohorizon-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glohorizon-api
    ports:
      - "5080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro

networks:
  glohorizon-network:
    driver: bridge